### ISSUE TITLE
테스트..

### ISSUE THREAD

**Issue by bettersan** [JiHeon-Park/DDD_STUDY#1]
43P '엔티티를 구현한 클래스는 다음과 같이 식별자를 이용해서 equals()메서드와 hashCode()메서드를 구현할 수 있다.'

라며 Order에 hashCode 메소드를 만드는데 eqauls는 목적과 사용용도가 이해가 가는데 
hashCode메소드는 왜 만들어야하는지 언제 쓰려고 하는건지 궁금함이 듭니다.

**Comment by JiHeon-Park** [comment]
hashCode 는 엔터티 클래스를 고유한 값으로 구분하기 위한 것.
